version: '3.4'
services:
  php:
    build:
      context: ../../
      dockerfile: ./automation/.docker/php/Dockerfile
      target: dev
    volumes:
      - '../../:/var/www/html'
    environment:
      - 'APP_ENV=dev'
      - 'DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}'
    ports:
      - '${APP_LOCAL_PORT}:8080'
    restart: 'on-failure:5'

  mysql:
    image: 'mysql:8.0'
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--lower_case_table_names=1'
    volumes:
      - 'mysql-data:/var/lib/mysql:delegated'
    ports:
      - '${MYSQL_LOCAL_PORT}:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
    restart: 'on-failure:5'

  redis:
    image: 'redis:5.0-alpine'
    restart: 'on-failure:5'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:5.0'
    environment:
      - 'PMA_HOST=mysql'
      - 'PMA_USER=root'
      - 'PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}'
    restart: 'on-failure:5'
    ports:
      - '${PMA_LOCAL_PORT}:80'
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local
