name: Build container and publish to Web App

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: azuredemomai.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . --file=automation/.docker/php/Dockerfile -t azuredemomai.azurecr.io/phpdemoapp:${{ github.run_id }}
        docker push azuredemomai.azurecr.io/phpdemoapp:${{ github.run_id }}
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'maidemo'
        images: 'azuredemomai.azurecr.io/phpdemoapp:${{ github.run_id }}
    
    - name: Azure logout
      run: |
        az logout